### ISSUE TITLE
[BE] fix: FastAPI 서버 배포 과정 확인 

### ISSUE THREAD

**Issue by cheesecat47** [d102-preview/preview#136]
## 🚧 Description
FastAPI 배포 서버가 업데이트 되면서 빌드, 배포 과정 수정 필요. 문서화도 추가로 필요.

## ✅ Todo
- [x] 빌드, 배포 과정 확인
  - [x] 환경 변수 확인
  - [x] Docker 빌드 확인
  - [ ] 배포 후 접속 확인
- [ ] 포팅매뉴얼 등 문서 업데이트
