### ISSUE TITLE
[FE] feat: 공통질문 스크립트 작성 API 통신

### ISSUE THREAD

**Issue by danbxx22** [d102-preview/preview#176]
## 🚧 Description

사용자는 공통 질문 상세 조회에서 스크립트를 작성할 수 있다.

## ✅ Todo
- [x] 스크립트 작성 API 연동
- [x] 스크립트가 비어있을 시 '수정'이 아닌 '작성'으로 보이게 하기 
- [x] 스크립트 제한 글자 수  constant  파일에 정의하기
