### ISSUE TITLE
[FE] feat: 꼬리 질문 요청 API 통신

### ISSUE THREAD

**Issue by hyun812** [d102-preview/preview#204]
## 🚧 Description
사용자는 대답한 답변에 대한 꼬리 질문을 확인 할 수 있다.

## ✅ Todo
- [x] 꼬리 질문 요청 mock data 구현
- [x] 꼬리 질문 요청 mock handler 구현
- [x] 꼬리 질문 요청 API 통신
