### ISSUE TITLE
[FE] feat: 분석 결과 목록 조회 API 통신

### ISSUE THREAD

**Issue by danbxx22** [d102-preview/preview#218]
## 🚧 Description

사용자는 분석 결과 페이지에서 세트별로 분석 결과 목록을 확인할 수 있다.   

## ✅ Todo
- [x] 분석 결과 목록 조회 API 통신
- [ ] 결과 분석 중 처리
- [ ] 분석 불가 영상 처리
