### ISSUE TITLE
 [FE] feat: modal 컴포넌트 구현

### ISSUE THREAD

**Issue by hyun812** [d102-preview/preview#22]
## 🚧 Description
공통 컴포넌트인 modal 컴포넌트를 구현한다.

## ✅ Todo
- [x] modal 컴포넌트 구현
- [x] modal 컴포넌트 스토리북 구현
- [x] modal 애니메이션 구현
