### ISSUE TITLE
 [FE] feat: 면접 진행 페이지 기본 UI 구현

### ISSUE THREAD

**Issue by hyun812** [d102-preview/preview#23]
## 🚧 Description
사용자는 면접 진행 페이지를 확인 할 수 있다.

## ✅ Todo
- [x] 면접 진행 페이지 기본 UI 구현
- [x] 타이머 기능 구현
- [x] 면접 질문 컴포넌트 구현
