### ISSUE TITLE
[INFRA] deploy: 배포서버 관련 설정

### ISSUE THREAD

**Issue by hoing97s** [d102-preview/preview#31]
## 🚧 Description

배포와 관련된 설정을 마친다.

## ✅ Todo
- [x] 포팅메뉴얼 작성
- [x] Redis 도커 컴포즈 파일 작성
- [x] MariaDB 도커 컴포즈 파일 작성
- [x] Jenkisn 도커 컴포즈 파일 작성
- [x] NGINX 설정 파일 작성
- [x] 쉘(실행) 스크립트 작성
