### ISSUE TITLE
[FE] feat: 실전 면접 질문 API 모킹 구현

### ISSUE THREAD

**Issue by hyun812** [d102-preview/preview#66]
## 🚧 Description
사용자는 실전 면접 질문 임시 데이터를 API 모킹을 통해  확인할 수 있다.

## ✅ Todo
- [x] API Mock Data 생성
- [x] API 데이터 통신 구현
- [x] Tanstack Query 구현
