### ISSUE TITLE
[BE] refactor: 로그 관련 파일 수정 및 health check API 수정

### ISSUE THREAD

**Issue by hoing97s** [d102-preview/preview#67]
## 🚧 Description

로그관련 파일을 수정한다.
CI/CD 관련 health check API url 및 파이프라인을 수정한다.

## ✅ Todo
- [x] logback.yml 수정
- [x] health check API url 수정
- [x] 파이프 라인 수정
