### ISSUE TITLE
[AI] feat: KoBERT 모델 학습을 위한 데이터 전처리 

### ISSUE THREAD

**Issue by cheesecat47** [d102-preview/preview#71]
## 🚧 Description

 KoBERT 모델 학습을 위해 데이터를 전처리 합니다. 

## ✅ Todo

- [x] 문장 - 클래스 라벨링
- [x] `id, document, label`로 컬럼명 수정
- [x] `label` 컬럼은 문자열이 아니라 정수형으로 변경
