### ISSUE TITLE
 [FE] feat: 면접 진행 로직 구현

### ISSUE THREAD

**Issue by hyun812** [d102-preview/preview#75]
## 🚧 Description
사용자는 실전 면접을 진행할 수 있다

## ✅ Todo
- [x] 면접 진행 로직 구현
- [x] 파일 업로드 애니메이션 및 UI 구현
- [x] 배경 blur 효과 구현
- [x] 녹화 대기 화면 UI 구현

## 🛠️삽질로그

면접 진행 로직 구현에 있어 각각의 상태로 구분하여 UI 변경하도록 함
  -  stream 연결 전 상태는 stream으로 판단
  -  pending -> 카메라, 마이크 세팅 중 (사용자가 파란색 다음버튼을 눌렀을 때 다음 상태로 변경)
  -  preparing -> 질문을 받아와 녹화대기 중인 상태 (사용자가 녹화시작 버튼을 눌렀을 때 다음 상태로 변경)
  -  recording -> 이후 RecordTimer 컴포넌트에서 카운트 다운 시작하고 종료하면 녹화 시작
  -  proceeding -> 녹화 진행중인 상태
  -  uploading -> 녹화한 영상을 서버에 업로드하는 중 (사용자가 직접 다음을 누르거나 타이머가 다 지났을 때 다시 recording 상태로 변경)
