### ISSUE TITLE
[BE] feat: 공통 카테고리 CRUD 구현

### ISSUE THREAD

**Issue by nmhojo** [d102-preview/preview#78]
## 🚧 Description

공통 카테고리 CRUD 관련 기능을 구현한다.

## ✅ Todo
- [ ] 공통 카테고리 생성 구현
- [ ] 공통 카테고리 조회 구현
- [ ] 공통 카테고리 수정 구현
- [ ] 공통 카테고리 삭제 구현
