### ISSUE TITLE
[FE] feat: 회원가입 API 모킹

### ISSUE THREAD

**Issue by rosielsh** [d102-preview/preview#81]
## 🚧 Description
사용자는 회원가입을 할 수 있다.

## ✅ Todo
- [x] MSW 코드 작성
- [x] react query hooks 작성
- [x] 회원가입 후 로그인 페이지로 이동
